ci_test/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from ci_test import views
urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.HomePage.as_view(), name='homepage'),
    re_path(r'^goodbye/$', views.GoodBye.as_view(), name='goodbye'),
    re_path(r'^welcome/$', views.Welcome.as_view(), name='welcome'),
    re_path(r'^users/', include('users.urls', namespace='user')),
    re_path(r'^users/', include('django.contrib.auth.urls')),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from users import views

app_name = 'users'

urlpatterns = [
    url(r'signup/$', views.SignUp.as_view(), name='signup'),
    url(r'login/$', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    url(r'logout/$', auth_views.LogoutView.as_view(), name='logout'),
]

users/models.py
from django.db import models
from django.contrib import auth
from django.utils import timezone
# Create your models here.

class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.usermame)

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

ci_test/views.py
from django.views.generic import TemplateView
from django.urls import reverse
from django.http import HttpResponseRedirect


class HomePage(TemplateView):
    template_name = 'index.html'


class GoodBye(TemplateView):
    template_name = 'goodbye.html'

class Welcome(TemplateView):
    template_name = 'welcome.html'

users/views.py
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms


class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "users/signup.html"

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>My Website</title>
    <!-- Bootstrap CDN links  -->
    <!-- CSS & JS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <!-- jQuery & Popper.js -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

  </head>
  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
<div class="container" dir="ltr">
  <a href="{% url 'homepage' %}" class="navbar-brand">My Website</a>
  <button class="navbar-toggler" data-toggle="collapse" data-target="#navNavbar"><span class="navbar-toggler-icon"></span></button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
      <li class="nav-item active">
        <a href="{% url 'homepage' %}" class="nav-link">Home</a>
      </li>

      <li class="nav-item active">
        <a href="#" class="nav-link">Podcast</a>
      </li>
      <li class="nav-item active">
        <a href="#" class="nav-link">Channels</a>
      </li>
      <li class="nav-item active">
        <a href="#" class="nav-link">Create channel</a>
      </li>
      <li class="nav-item active">
        <a href="" class="nav-link">MyProfile</a>
      </li>
      <li class="nav-item active">
        <a href="" class="nav-link">Welcome: {{request.user.username}}</a>
      </li>
      <li><a href="{% url 'user:logout'%}" class="btn btn-simple">Log out</a></li>
      {% else %}

      <li class="nav-item active">
        <a href="" class="nav-link">Home</a>
      </li>
      <li class="nav-item active">
        <a href="#" class="nav-link">Channels</a>
      </li>
      <li><a href="{% url 'user:login' %}" class="btn btn-simple">Log in</a></li>
      <li><a href="{% url 'user:signup' %}" class="btn btn-simple">Sign up</a></li>
      {% endif %}

    </ul>
  </div>
</div>
</nav>
<div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>
  </body>

</html>

templates/goodbye.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>Successfully Logout</h1>
    <h2>Come back soon. We miss you!</h2>
    <a class="btn btn-primary" href="{% url 'homepage' %}">Goto HomePage</a>

  </div>

</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to My Website</h1>
    <h2>Signup for create channel and upload podcasts!</h2>
    <h3>You can join to a channel and listen to the podcasts.</h3>


  </div>

</div>

{% endblock %}

templates/welcome.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to My Website</h1>
    <h2>You can now create Channel and Podcasts</h2>
    <a class="btn btn-primary" href="{% url 'homepage'%}">Goto HomePage</a>
    <!-- <input  class="btn btn-primary" type="button" value="Goto HomePage"> -->
  </div>

</div>

{% endblock %}

users/templates/users/login.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
<div class="container">
  <h1>Login</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
      <input type="submit" value="Login" class="btn btn-default">
  </form>
</div>
{% endblock %}

users/templates/users/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static '/css/signup.css' %}">

<div class="page-container">

            <form method="POST">
              {% csrf_token %}
              {% bootstrap_form form %}
              <input class="btn btn-primary" type="submit" name="" value="submit">
            </form>
</div>

{% endblock %}
}